development:
  adapter: sqlite3
  database: portfolio_development
  pool: 5
test:
  adapter: sqlite3
  database: portfolio_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: portfolio_production
  pool: 5
  timeout: 5000
  username: postgres
  password: kuzmich1987